version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: shareitdb
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"